[project]
name = "prompt-inject"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fitz>=0.0.1.dev2",
    "frontend>=0.0.3",
    "jupyter>=1.1.1",
    "litellm>=1.74.8",
    "numpy>=2.3.1",
    "torch>=2.7.1",
]
